# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='description',
            field=models.CharField(db_column='소개', default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='isVote',
            field=models.BooleanField(db_column='후보', default=False),
        ),
    ]
