# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='prize',
            field=models.NullBooleanField(db_column='우승이력'),
        ),
    ]
