# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0002_auto_20180719_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='prize_date',
        ),
    ]
