# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0004_auto_20180721_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 7, 22, 7, 6, 47, 610617, tzinfo=utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2018, 7, 29, 7, 6, 46, 610617, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp.VoteDate')),
            ],
        ),
    ]
