# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0005_votedate_voteresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedate',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 7, 14, 25, 144487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='votedate',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 7, 14, 26, 144487, tzinfo=utc)),
        ),
    ]
