# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0009_auto_20180803_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedate',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 15, 31, 41, 437697)),
        ),
        migrations.AlterField(
            model_name='votedate',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 15, 31, 42, 437697)),
        ),
    ]
